image_task:
  persistent_worker:
    isolation:
      container:
        image: debian:latest
        cpu: 0.5
        memory: 512
        volumes:
          - /root/.ccache:/root/.ccache

  script: uname -a

dockerfile_task:
  persistent_worker:
    isolation:
      container:
        dockerfile: ./Dockerfile
        cpu: 0.5
        memory: 512
        volumes:
          - /root/.ccache:/root/.ccache

  resources:
    docker: 1
  script: uname -a

  env:
    CIRRUS_ARCH: amd64
    CIRRUS_OS: linux
